sudo: false
os:
- linux
language: haskell
cache:
  directories:
  - "$HOME/.stack"
before_install:
- sudo add-apt-repository -y ppa:hvr/ghc
- sudo apt-get update
- sudo apt-get install cabal-install-3.0
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack build
- stack haddock
script:
- stack --no-terminal --skip-ghc-check test
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
deploy:
- provider: script
  script: bash deploy.sh "$HACKAGE_USER" "$HACKAGE_PASSWORD"
  on:
    tags: true
- provider: pages
  local_dir: "$(stack path --local-doc-root)"
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    tags: true
env:
  global:
  - secure: r9AbNLgfJhVwwBndZ3NiVhd30sReqN9NMZ4TnYCeJ5VJQpj3upkE4T+E7DWH+UakF5BbX3aYSkfCMwRbXe9oOfhawxt8qXE/O6zrC5IRwd+OM9sKMpVr223w5nVx43gM1zam8OMCd1SodrzvlacDqLsbLXAsSTEr5QUVJro//q17iY7Mq9LLMfOs7B8fTQ7ZYKvBh/BnT7wKSlTO18HuwQUJs+BL9lYK35oXIkmmpA5RIcGATQ2wKBR9w8K8iUQxbOVdzfyf0B7MLLKRQjSnF1rJ+2AF0T4xtTDxF4wrfJmKCsYLHne5STFPHkZkcfbp7Vd8nuHMFCvTucqHhtzLm2ZJdKbeKX0BKV/XcWA9PjrqtkpiXi3YEMhlAxu0gkY9KBHLfd5LKl76PaXbjmaHne5uCqvEPjstEN5jySnR2xcnDml6EDe5hpAQ8NTmTIWboDWaLFv0ZHncTm7fQGYCQ+95J9H08+IIKHo+hZ+w3dRH4l+6ZS9QXOzhGy9fnh/99KKtShFvooxdgfbDghS9+aSGZotyrN+zHLHGDU/Z61+3mmmGFntImGqAlkTEAzXD85N8kTNo/71wdqlX9WuZbVgxjStHs7KAXw3FUnOp7TdjLSC5gD6Bro4+0wWPqtt961fY8eCN/3rBTjnbToXYVyz64SBrPL6+YYMKGoeIpVs=
  - secure: VxgGRQoSzGz/+nrePmai7NHOUr5OkPWvj0YkkY+JRJPwTgn8E0TkVRq5/H4DcY4Pxa2CoZVTBYDqecz4rMK7/9oZkd7Cn1C2ysDAMWgA7Ft1YlLgwK08exVtc2481gtJFbn/UlrDSJSn3Rm4HZO/3YNxwy/aAZs+iQvxcWFusC578yuQH5HF2Z0nTtrz7YhoYkWpS+ry+QzV4T+6aRZLq1GhKvoB4vDiW3Bu5WLWLsFWfFlNakNqH/DNKZCrdeAXMu7bsb7CBeUm4SN+L07rnODk5T4ZOUngCm6O/M4ueWP0MSwoNswH0ynrLrx3igCZM5qOHTuLvI9YfxBhTpxny0HTCxBIdyQey9PQFkTk+pTykww6PFl5GTzXABGkq+p/zoPPNRcZUTaXQDtBOLWTOYhbHiGmjo6/cwp6xJSWfSaKzvt222h3oNqCnZr5ZJzc47hpDvgvkue0x35YQk76GTF6DW05Tt0cAnmuwZiJs98qEcXJwnFIdP1Zo28/z9wPeHzwHQsJta2wWtYpMM3nQ5PKn9bQMnzk31+FuLik9GwkbGTcC43ouSt7J/lEX/lcFRvMAjj4LlfESpwnxsN23J86Eb+RojBkn2SR92iEObo3QX0E1SjpJyMjot/edObmLry2SU1uWxKfM2OOAKTQL3if7QU02nJST6mRWgPCvUw=
  - secure: MEWRghKNIFt72NjWOmFOUR/o3S0Eg4GUOa37tRAR7pWhBcbazLi9TjJkd/wtVybmxpJjKC4WCh6PsDVZwq1Gzu1E1j9DdMlnSIRHRdeKOyPgpPLWu31Gh9UocAcgPIwwPQUW/ZjFXodhrGbM7JPlbCq6FIxxQtgEWxeQFSJw/7oWfBKYTN65K0XWn9WtQjY/Y5ndMZbE0X8GhRgtkN2/su5SJ8Pcgj9k8CdqPMiPLTRN+Gqr+twNvwf1Xye4Knzc5y86L+RzUEnZydePVXF0EBlB9B8Sq8GvAt8k74gAaXxXsForeh7X+doR/vkMSB1cscsernk0JMgKeRJ1LUYZ7HJjx5OAAS4v5J4CNPAzuKVpXOsb30oLK+rRvoM7mkMkougeWdxE/l/tPQ8kN01ZK6SpMqThbQajGq8RJeEP4N53U9XRWv2x6T18RPokgbS2aL8IFV2FAlSyv5CPvF01SGQe8TbO3BkP26dnshcOYB0ExKzTzKmwsUn6960XGDgXogfyvz1rD5lNncya6RQm7MAFE6bJstgIcwDhZAHAcBdkIIVgggIFpqZPaJ4RBBArCF7tDE8cbVk1QHRLs59s1Q2RMILJxKNbDxCO7SyBYSt0DUHyq5cGJcBXYf6xb1JchzrsG0on7mKZ5XI6OQbAGnNwz2CVeLoC7McnKfb0Z2c=
