name: Standard checks and deployment
on: push

jobs:
  linux1:
    name: Build the Haskell software
    runs-on: ubuntu-latest
    steps:
    - name: add ppa
      run: sudo add-apt-repository -y ppa:hvr/ghc
    - name: update package database
      run: sudo apt-get update
    - name: install required packages
      run: sudo apt-get cabal-install-3.0 haskell-stack
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: build the Haskell software
      run: stack build --ghc-options='-Wall -Werror'

jobs:
  linux2:
    name: Build the Haddock documentation
    runs-on: ubuntu-latest
    steps:
    - name: add ppa
      run: sudo add-apt-repository -y ppa:hvr/ghc
    - name: update package database
      run: sudo apt-get update
    - name: install required packages
      run: sudo apt-get cabal-install-3.0 haskell-stack
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: build the Haskell software
      run: "! stack haddock --force-dirty 2>&1 | grep -P '^\\s*[0-9]{1,2}%'"

  linux3:
    name: Look for todos
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: look for todos
      run: "! grep -i -P 'TODO|[?]{3,}' $(find src -iname '*.hs')"
