name: Standard checks and deployment
on: push

jobs:
  linux1:
    name: Build the Haskell software
    runs-on: ubuntu-latest
    steps:
    - name: build haskell project
      uses: hapytex/github-actions/build-haskell-project@master

  linux2:
    name: Build the Haddock documentation
    runs-on: ubuntu-latest
    steps:
    - name: set up Haskell environment
      uses: hapytex/github-actions/setup-haskell@master
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: build the Haddock documentation
      run: "! stack haddock --force-dirty 2>&1 | grep -P '^\\s*[0-9]{1,2}%'"

  linux3:
    name: Look for todos
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: look for todos
      uses: hapytex/github-actions/look-for-todos@master
      with:
        directory: src


  linux4:
    name: Check for hlint suggestions
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: look for hlint suggestions
      run: curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .

  linux5:
    name: Run the tests
    runs-on: ubuntu-latest
    steps:
    - name: set up Haskell environment
      uses: hapytex/github-actions/setup-haskell@master
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: run the tests of the package
      run: stack --no-terminal --skip-ghc-check test

  linux6:
    name: Deploy documentation to GitHub pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: hapytex/github-actions/setup-haskell@master
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: create the haddock documentation
      run: stack haddock --force-dirty
    - name: retrieve path to the documentation
      run: echo "haddock_path=$(stack path --local-doc-root)" >> $GITHUB_ENV
    - name: deploy the documentation on the GitHub pages
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: "${{ env.haddock_path }}"
